# Supabase 연결 설정
SUPABASE_URL = "https://txlkfywysdnoigcwbags.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bGtmeXd5c2Rub2lnY3diYWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTU4NDEsImV4cCI6MjA2OTE5MTg0MX0.svkW2EFuqUTfomf8_FDRhdghfCC5_NbmF1zEXhI3TD0"

# 기존 API 키들
GENAI_API_KEY = "AIzaSyD69-wKYfZSID327fczrkx-JveJdGYIUIk"
TEAMS_WEBHOOK_URL = "https://poscoenc365.webhook.office.com/webhookb2/f6efcf11-c6a7-4385-903f-f3fd8937de55@ec1d3aa9-13ec-4dc5-8672-06fc64ca7701/IncomingWebhook/1fb9d9ce7f4c4093ba4fe9a8db67dc2f/1a2e3f7d-551b-40ec-90a1-e815373c81a7/V2qbqRtbAap4il8cvVljyk_ApZuHTDE0AfOYLQ8V9SqQs1" 

KMA_API_KEY = "srgpo0t7uDjbNhm4WIIX4RVzvVowMmqeSsJ7Y0Sg2XmHWjTUu%2BXou%2FuSFiLcKEvKpAoJhIKsNRVlcXcNh%2Fjm1Q%3D%3D"